EduHomeAPanel/Models/Blog.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace EduHomeAPanel.Models
{
    public class Blog
    {
        [Key]
        public int Id { get; set; }
        [MaxLength(250)]
        public string BgImage { get; set; }
        [NotMapped]
        public IFormFile ImageFile { get; set; }
        public string Title { get; set; }
        public DateTime CreatedDate { get; set; }
        List<BlogDetail> BlogDetails { get; set; }
    }
}

EduHomeAPanel/Models/BlogDetail.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace EduHomeAPanel.Models
{
    public class BlogDetail
    {
        [Key]
        public int Id { get; set; }
        [MaxLength(250)]
        public string Image { get; set; }
        [NotMapped]
        public IFormFile ImageFile { get; set; }
        [MaxLength(150)]
        public string Title { get; set; }
        [Column(TypeName = "ntext")]
        public string Text { get; set; }
        public DateTime CreatedDate { get; set; }
        [ForeignKey("Blog")]
        public int BlogId { get; set; }
        public Blog Blog { get; set; }
    }
}

EduHomeAPanel/Models/ErrorViewModel.cs
using System;

namespace EduHomeAPanel.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EduHomeAPanel/Models/Message.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EduHomeAPanel.Models
{
    public class Message
    {
        [Key]
        public int Id { get; set; }
        [MaxLength(50)]
        public string Title { get; set; }
        [MaxLength(250)]
        public string Content { get; set; }
        [MaxLength(50)]
        public string Name { get; set; }
        [MaxLength(150)]
        public string Email { get; set; }
        [MaxLength(1000)]
        public string Subject { get; set; }
        public string Text { get; set; }
        [MaxLength(50)]
        public string Address { get; set; }
        public DateTime CreatedDate { get; set; }
    }
}

EduHomeAPanel/Models/NewsLetter.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EduHomeAPanel.Models
{
    public class NewsLetter
    {
        [Key]
        public int Id { get; set; }
        [MaxLength(50)]
        public string Title { get; set; }
        [MaxLength(50)]
        public string SubTitle { get; set; }
        [MaxLength(50)]
        public string Email { get; set; }
        public DateTime CreatdeDate { get; set; }
    }
}

EduHomeAPanel/Models/Setting.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace EduHomeAPanel.Models
{
    public class Setting
    {
        [Key]
        public int Id { get; set; }
        [MaxLength(250)]
        public string LogoImage { get; set; }
        [NotMapped]
        public IFormFile IformFile { get; set; }
        [MaxLength(50)]
        public string Address { get; set; }
        [MaxLength(100)]
        public string Phone { get; set; }
        [MaxLength(50)]
        public string Email { get; set; }
        [MaxLength(250)]
        public string WebSite { get; set; }
    }
}

EduHomeAPanel/Models/Social.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EduHomeAPanel.Models
{
    public class Social
    {
        [Key]
        public int Id { get; set; }
        [MaxLength(50)]
        public string Name { get; set; }
        [MaxLength(30)]
        public string Icon { get; set; }
        [MaxLength(250)]
        public string Link { get; set; }
    }
}

EduHomeAPanel/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EduHomeAPanel.Areas.Admin.Controllers
    
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

EduHomeAPanel/Areas/Admin/Controllers/NewsLetterController.cs
using EduHomeAPanel.DATA;
using EduHomeAPanel.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EduHomeAPanel.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class NewsLetterController : Controller
    {
        private readonly AppDbContext _context;

        public NewsLetterController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            List<NewsLetter> model = _context.NewsLetters.ToList();
            return View(model);
        }

        public IActionResult Create()
        {
            List<NewsLetter> model = _context.NewsLetters.ToList();
            return View(model);
        }
        [HttpPost]
        public IActionResult Create(string Title, string SubTitle, string Email, DateTime CreatdedDate)
        {
            List<NewsLetter> model = _context.NewsLetters.ToList();
            return View(model);
        }


    }
}

EduHomeAPanel/Controllers/BlogController.cs
using EduHomeAPanel.DATA;
using EduHomeAPanel.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EduHomeAPanel.Controllers
{
    public class BlogController : Controller
    {
        private readonly AppDbContext _context;

        public BlogController (AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {

            List<Blog> blog = this._context.Blogs.ToList();
            return View(blog);
            
        }
    }
}

EduHomeAPanel/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EduHomeAPanel.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

EduHomeAPanel/Controllers/HomeController.cs
using EduHomeAPanel.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace EduHomeAPanel.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

       

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EduHomeAPanel/Controllers/NewsLetterController.cs
using EduHomeAPanel.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EduHomeAPanel.Controllers
{
    public class NewsLetterController : Controller
    {
        private readonly object _context;

        public IActionResult Index()
            {

            List<NewsLetter> newsletter = this._context.NewsLetters.ToList();
                return View(newsletter);

            }
           
        
    }
}

EduHomeAPanel/Areas/Admin/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";

}

EduHomeAPanel/Areas/Admin/Views/NewsLetter/Create.cshtml
@model NewsLetter
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-lg-6">
            <form asp-area="Admin" asp-controller="NewsLetter" asp-action="Create" method="post">
                <div class="mb-3">
                    <label asp-for="@Model.Title" class="form-label">Title</label>
                    <input class="form-control" asp-for="@Model.Title">
                    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
                </div>
                <div class="mb-3 ">
                    <input class="form-check-input" asp-for="@Model.SubTitle">
                    <label class="form-check-label" asp-for="@Model.SubTitle">Sub Title</label>
                </div>
                <div class="mb-3">
                    <input class="form-check-input" asp-for="@Model.Email">
                    <label class="form-check-label" asp-for="@Model.Email">Email</label>
                </div>
                <div class="mb-3">
                    <input class="form-check-input" asp-for="@Model.CreatdeDate">
                    <label class="form-check-label" asp-for="@Model.CreatdeDate">Created Date</label>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>

EduHomeAPanel/Areas/Admin/Views/NewsLetter/Index.cshtml
@model List<NewsLetter>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Title</th>
                        <th scope="col">Sub Title</th>
                        <th scope="col">Email</th>
                        <th scope="col">CreatedDate</th>

                    </tr>
                </thead>
                <tbody>

                    @{ int i = 0;
                        foreach (var item in Model)
                        {
                            i++;
                            <tr>
                                <th scope="row">@i</th>
                                <td>@item.Title</td>
                                <td>@item.SubTitle</td>
                                <td>@item.Email</td>
                                <td>@item.CreatdeDate</td>

                            </tr>

                        }

                    }



                </tbody>
            </table>
            <div>
                <a class="btn btn-primary" asp-area="Admin" asp-controller="NewsLetter" asp-action="Create">Create</a>
            </div>
        </div>
    </div>
</div>

EduHomeAPanel/Views/Blog/Index.cshtml
@model List<Blog>
@{
    ViewData["Title"] = "Index";
}

<div class="banner-area-wrapper">
    <div class="banner-area text-center">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="banner-content-wrapper">
                        <div class="banner-content">
                           
                            <h2>Blog</h2>
            
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Banner Area End -->
<!-- Blog Start -->
<div class="blog-area pt-150 pb-150">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-6 col-xs-12">
                <div class="single-blog mb-60">
                    <div class="blog-img">
                        <a href="#"><img src="img/blog/blog1.jpg" alt="blog"></a>
                        <div class="blog-hover">
                            <i class="fa fa-link"></i>
                        </div>
                    </div>
                    <div class="blog-content">
                        <div class="blog-top">
                            <p>By Alex  /  June 20, 2017  /  <i class="fa fa-comments-o"></i> 4</p>
                        </div>
                        <div class="blog-bottom">
                            <h2><a href="blog-details.html">I must explain to you how all this a mistaken idea </a></h2>
                            <a href="blog-details.html">read more</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6 col-xs-12">
                <div class="single-blog mb-60">
                    <div class="blog-img">
                        <a href="#"><img src="img/blog/blog2.jpg" alt="blog"></a>
                        <div class="blog-hover">
                            <i class="fa fa-link"></i>
                        </div>
                    </div>
                    <div class="blog-content">
                        <div class="blog-top">
                            <p>By Alex  /  June 20, 2017  /  <i class="fa fa-comments-o"></i> 4</p>
                        </div>
                        <div class="blog-bottom">
                            <h2><a href="blog-details.html">I must explain to you how all this a mistaken idea </a></h2>
                            <a href="blog-details.html">read more</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6 col-xs-12">
                <div class="single-blog mb-60">
                    <div class="blog-img">
                        <a href="#"><img src="img/blog/blog3.jpg" alt="blog"></a>
                        <div class="blog-hover">
                            <i class="fa fa-link"></i>
                        </div>
                    </div>
                    <div class="blog-content">
                        <div class="blog-top">
                            <p>By Alex  /  June 20, 2017  /  <i class="fa fa-comments-o"></i> 4</p>
                        </div>
                        <div class="blog-bottom">
                            <h2><a href="blog-details.html">I must explain to you how all this a mistaken idea </a></h2>
                            <a href="blog-details.html">read more</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6 col-xs-12">
                <div class="single-blog mb-60">
                    <div class="blog-img">
                        <a href="#"><img src="img/blog/blog4.jpg" alt="blog"></a>
                        <div class="blog-hover">
                            <i class="fa fa-link"></i>
                        </div>
                    </div>
                    <div class="blog-content">
                        <div class="blog-top">
                            <p>By Alex  /  June 20, 2017  /  <i class="fa fa-comments-o"></i> 4</p>
                        </div>
                        <div class="blog-bottom">
                            <h2><a href="blog-details.html">I must explain to you how all this a mistaken idea </a></h2>
                            <a href="blog-details.html">read more</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6 col-xs-12">
                <div class="single-blog mb-60">
                    <div class="blog-img">
                        <a href="#"><img src="img/blog/blog5.jpg" alt="blog"></a>
                        <div class="blog-hover">
                            <i class="fa fa-link"></i>
                        </div>
                    </div>
                    <div class="blog-content">
                        <div class="blog-top">
                            <p>By Alex  /  June 20, 2017  /  <i class="fa fa-comments-o"></i> 4</p>
                        </div>
                        <div class="blog-bottom">
                            <h2><a href="blog-details.html">I must explain to you how all this a mistaken idea </a></h2>
                            <a href="blog-details.html">read more</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6 col-xs-12">
                <div class="single-blog mb-60">
                    <div class="blog-img">
                        <a href="#"><img src="img/blog/blog6.jpg" alt="blog"></a>
                        <div class="blog-hover">
                            <i class="fa fa-link"></i>
                        </div>
                    </div>
                    <div class="blog-content">
                        <div class="blog-top">
                            <p>By Alex  /  June 20, 2017  /  <i class="fa fa-comments-o"></i> 4</p>
                        </div>
                        <div class="blog-bottom">
                            <h2><a href="blog-details.html">I must explain to you how all this a mistaken idea </a></h2>
                            <a href="blog-details.html">read more</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6 hidden-xs">
                <div class="single-blog">
                    <div class="blog-img">
                        <a href="#"><img src="img/blog/blog7.jpg" alt="blog"></a>
                        <div class="blog-hover">
                            <i class="fa fa-link"></i>
                        </div>
                    </div>
                    <div class="blog-content">
                        <div class="blog-top">
                            <p>By Alex  /  June 20, 2017  /  <i class="fa fa-comments-o"></i> 4</p>
                        </div>
                        <div class="blog-bottom">
                            <h2><a href="blog-details.html">I must explain to you how all this a mistaken idea </a></h2>
                            <a href="blog-details.html">read more</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6 hidden-xs">
                <div class="single-blog">
                    <div class="blog-img">
                        <a href="#"><img src="img/blog/blog8.jpg" alt="blog"></a>
                        <div class="blog-hover">
                            <i class="fa fa-link"></i>
                        </div>
                    </div>
                    <div class="blog-content">
                        <div class="blog-top">
                            <p>By Alex  /  June 20, 2017  /  <i class="fa fa-comments-o"></i> 4</p>
                        </div>
                        <div class="blog-bottom">
                            <h2><a href="blog-details.html">I must explain to you how all this a mistaken idea </a></h2>
                            <a href="blog-details.html">read more</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 hidden-sm col-xs-12">
                <div class="single-blog">
                    <div class="blog-img">
                        <a href="#"><img src="img/blog/blog9.jpg" alt="blog"></a>
                        <div class="blog-hover">
                            <i class="fa fa-link"></i>
                        </div>
                    </div>
                    <div class="blog-content">
                        <div class="blog-top">
                            <p>By Alex  /  June 20, 2017  /  <i class="fa fa-comments-o"></i> 4</p>
                        </div>
                        <div class="blog-bottom">
                            <h2><a href="blog-details.html">I must explain to you how all this a mistaken idea </a></h2>
                            <a href="blog-details.html">read more</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <div class="pagination">
                    <ul>
                        <li><a href="#">1</a></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

EduHomeAPanel/Views/Contact/Index.cshtml
@{
    ViewData["Title"] = "Index";
}


<div class="banner-area-wrapper">
    <div class="banner-area text-center">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="banner-content-wrapper">
                        <div class="banner-content">
                            <h2>contact</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Banner Area End -->
<!-- Contact Start -->
<div class="map-area">
    <!-- google-map-area start -->
    <div class="google-map-area">
        <!--  Map Section -->
        <div id="contacts" class="map-area">
            <div id="googleMap" style="width:100%;height:440px;"></div>
        </div>
    </div>
</div>
<div class="contact-area pt-150 pb-140">
    <div class="container">
        <div class="row">
            <div class="col-md-5 col-sm-5 col-xs-12">
                <div class="contact-contents text-center">
                    <div class="single-contact mb-65">
                        <div class="contact-icon">
                            <img src="~/img/contact/contact1.png" alt="contact">
                        </div>
                        <div class="contact-add">
                            <h3>address</h3>
                            <p>135, First Lane, City Street</p>
                            <p>New Yourk City, USA</p>
                        </div>
                    </div>
                    <div class="single-contact mb-65">
                        <div class="contact-icon">
                            <img src="~/img/contact/contact2.png" alt="contact">
                        </div>
                        <div class="contact-add">
                            <h3>address</h3>
                            <p>135, First Lane, City Street</p>
                            <p>New Yourk City, USA</p>
                        </div>
                    </div>
                    <div class="single-contact">
                        <div class="contact-icon">
                            <img src="~/img/contact/contact3.png" alt="contact">
                        </div>
                        <div class="contact-add">
                            <h3>address</h3>
                            <p>135, First Lane, City Street</p>
                            <p>New Yourk City, USA</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-7 col-sm-7 col-xs-12">
                <div class="reply-area">
                    <h3>LEAVE A message</h3>
                    <p>I must explain to you how all this a mistaken idea of ncing great explorer of the rut the is lder of human happinescias unde omnis iste natus error sit volptatem </p>
                    <form id="contact-form" action="http://preview.hasthemes.com/eduhome/mail.php" method="post">
                        <div class="row">
                            <div class="col-md-12">
                                <p>Name</p>
                                <input type="text" name="name" id="name">
                            </div>
                            <div class="col-md-12">
                                <p>Email</p>
                                <input type="text" name="email" id="email">
                            </div>
                            <div class="col-md-12">
                                <p>Subject</p>
                                <input type="text" name="subject" id="subject">
                                <p>Massage</p>
                                <textarea name="message" id="message" cols="15" rows="10"></textarea>
                            </div>
                        </div>
                        <a class="reply-btn" href="#" data-text="send"><span>send message</span></a>
                        <p class="form-messege"></p>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

EduHomeAPanel/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

EduHomeAPanel/Views/NewsLetter/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>